### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by k0zyrev** [11Tuvork28/11tuvork28#1]
Hi, I just wanted to thank you for the work you did with your instance. It was truly great! 

It's a little unfortunate it happened so suddenly so I didn't have a chance to backup data, but eh, my own fault.

Wish you the best, and thank you again!

ps sorry for bothering you, just really wanted to thank you for the service you provided, that's the least I can do.

**Comment by AndromedaCLI** [comment]
What was the username you used? I can try if I find the time and motivation to get a friend to get u the data from the backup.
It would be a raw SQL dump if that is fine by you.
@k0zyrev

**Comment by Hytha36** [comment]
Hey,

since I don't want to write half a novel, I guess I'm staying short by mentioning that I can fully agree with k0zyrev.

Sadly, that also counts for the part of backing up the data, so I'd be really thankfully if you could do that for me either (wouldn't be much of a problem if that would take a couple of days).

Thanks and best regards,
Hytha36

**Comment by AndromedaCLI** [comment]
Please to you both and everyone else reading this, send me an email(Use the address on GH) with your username and password.
I need the password to verify that you are actually the owner of said data^^

I will do what I can in my current limited situation to get you the data.

**Comment by k0zyrev** [comment]
@11Tuvork28 that is very kind of you, thank you, but honestly in my case I don't think it's worth the effort. I though maybe if it would be as easy as to start the instance for a short time, I'd definitely use the opportunity to back up, but if you need to do some manual work, I'd rather not to bother you. But thanks again!

**Comment by Hytha36** [comment]
It's been around 2 weeks since I sent an email as written above, but didn't hear anything after that.

It's not like I want to stress or something like that, I just wanted to make sure it arrived and stuff^^
